#nombre de la APP
spring.application.name=cl.dsy1103despacho-service
#puerto donde se ejecuta: por defecto 8080
server.port = 8081

# Crea la BD vacía en phpMyAdmin antes de arrancar.
# Hibernate generará las tablas desde las entidades.
spring.datasource.url=jdbc:mysql://localhost:3307/despacho_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#update: crea las tablas si no existen, las actualiza
#si el modelo cambió. Esto es ideal para desarrollo local
#uy así entender lo que ocurre internamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
